### ISSUE TITLE
vizdoom proceses can remain even after Python process has exited

### ISSUE THREAD

**Issue by gdb** [openai/gym-doom#2]
This seems to be true after running the tests (i.e. `nose2`)

**Comment by ppaquette** [comment]
The environment needs to call self.game.close() to stop the vizdoom process.

Is it possible 1) to add a close() method on environments to perform those clean-up actions, and 2) to automatically call the close() method if a signal.SIGINT (Ctrl-C) is detected?

**Comment by gdb** [comment]
Oh interesting. Yes, a close method seems pretty sane to me. We should probably implement it similarly to the monitor, where it gets called in the monitor's destructor or atexit.

**Comment by ppaquette** [comment]
I'll take care of it (both for gym and gym-doom).

**Comment by jietang** [comment]
PR for this here: https://github.com/openai/gym/pull/102

**Comment by jietang** [comment]
now merged
