### ISSUE TITLE
Problem reseting enviroment after episode done and reward gained

### ISSUE THREAD

**Issue by bartio** [openai/gym-doom#4]
Having a problem to correctly reset gym-doom enviroment. When I want to work with DoomBasic and get reward for killing monster, problem with env.reset() occur. 

---

> in _reset self.game.new_episode()
> doom_py.vizdoom.doom_is_not_running_exception: Controlled ViZDoom instance is not running or not ready.

---

 Going through all steps without killing monster do not cause any error and reset enviroment correctly. My code is just copy from random agent

`logger = logging.getLogger()
    logger.setLevel(logging.INFO)

    env = gym.make('DoomBasic-v0' if len(sys.argv)<2 else sys.argv[1])
    agent = RandomAgent(env.action_space)

    # You provide the directory to write to (can be an existing
    # directory, but can't contain previous monitor results. You can
    # also dump to a tempdir if you'd like: tempfile.mkdtemp().
    outdir = '/tmp/random-agent-results'
    env.monitor.start(outdir, force=True)

    episode_count = 100
    max_steps = 20
    reward = 0
    done = False

    

    for i in range(episode_count):
        ob = env.reset()

        for j in range(max_steps):
            action = agent.act(ob, reward, done)
            ob, reward, done, _ = env.step(action)
            

            ob = env.render()
            print reward

            if done:
                print done
                break

    # Dump result info to disk
    env.monitor.close()`

**Comment by jietang** [comment]
Thanks for the report. Just tested and it appears to be fixed in master

Also gym-doom has been merged into github.com/openai/gym - please open any new issues on that project's page.
