### ISSUE TITLE
which doom?

### ISSUE THREAD

**Issue by zdx3578** [openai/gym-doom#5]
please give a link to that doom office site and version?

**Comment by bartio** [comment]
I think that this is based this one https://freedoom.github.io/screenshots.html

**Comment by jietang** [comment]
Yes this is based on VizDoom. We call that out more clearly in the README.md for the doom-py dependency repo (https://github.com/openai/doom-py). Please check it out and create a doom-py issue if you think our attribution should be improved (this repo is getting merged back into gym soon)
